title: Project

fields:
    - name: name
      title: Name
      required: true

    - name: repo_url
      title: Repo url
      placeholder: "git://github.com/user/project"

    - name: domain
      title: Domain
      placeholder: "advice.enodev.org"

    - name: template
      title: Deployment template
      choices:
        - [mongo, flask+mongo]
        - [pg, postgres+django]
        - [static, static pages]

      widget: select

    - name: ssh_key
      title: Deployment ssh key
      widget: text

    - name: status
      title: Status
  
    - name: rev
      title: Deployed revision

forms:
    - name: default
      fields: [name, status, domain, repo_url, template, ssh_key, rev]

    - name: add
      fields: [name, repo_url]
